spring:
  application:
    name: mall-api
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

server:
  port: 8011